name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v1
        - name: Login to DockerHub Registry
          run: echo ${{ secrets.DOCKER_HUB_SECRET }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
        #- name: Get the version
          #id: vars
          #run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
        - name: Build the tagged Docker image
          run: docker build . --file Dockerfile --tag bethancropp/testing_github_actions
        - name: Push the tagged Docker image
          run: docker push bethancropp/testing_github_actions
        - name: Check out the repo
        - uses: actions/checkout@v2
        - name: Run the build process with Docker
        - uses: addnab/docker-run-action@v3
          with:
                image: bethancropp/testing_github_actions
                options: -v ${{ github.workspace }}:/var/www
                run: |
                    composer install
                    npm install
                    npm run production
